reference: idbastar_v0

default:
  max_it: 1 # only one iterations, this is only for analysis.

unicycle1_v0:
  default:
    delta_0: .2
    num_primitives_0: 200

unicycle2_v0:
  default:
    delta_0: .3
    num_primitives_0: 400

# quad2d_v0:
#   default:
#     num_primitives_0: 500
#     delta_0: .45
