trials: 1
timelimit: 100
n_cores: 1 # -1=auto

problems:
  - unicycle_first_order_0/bugtrap_0
  - unicycle_second_order_0/bugtrap_0
  - quad2d/quad_bugtrap
  - car_first_order_with_1_trailers_0/bugtrap_0
  - quadrotor_0/quad_one_obs
  - quadrotor_0/window
  - quad2dpole/window


algs:
  - dbastar_v0_heu0
  - dbastar_v0_heu1
  - dbastar_v0_heuNO
