trials: 20
timelimit: 20
n_cores: -1 # -1=auto

problems:
  # # # #
  - unicycle1_v0/parallelpark_0
  - unicycle1_v0/bugtrap_0
  - unicycle1_v0/kink_0
  # # # # #
  - unicycle1_v1/kink_0
  - unicycle1_v2/wall_0
  # # # # # #
  - unicycle2_v0/kink_0
  - unicycle2_v0/parallelpark_0
  - unicycle2_v0/bugtrap_0
  # # # # # # #
  # - car1_v0/kink_0
  # - car1_v0/bugtrap_0
  # - car1_v0/parallelpark_0
  # # #
  # - quad2d_v0/empty_0
  # - quad2d_v0/empty_1
  # - quad2d_v0/quad_obs_column
  # - quad2d_v0/quad_bugtrap
  # - quad2d_v0/quad2d_recovery_wo_obs
  # - quad2d_v0/quad2d_recovery_obs
  # - quad2d_v0/fall_through
  #
  # - quad2dpole_v0/move_with_down
  # - quad2dpole_v0/move_with_up
  # - quad2dpole_v0/up
  # - quad2dpole_v0/down
  # - quad2dpole_v0/up_obs
  # - quad2dpole_v0/window_easy
  # - quad2dpole_v0/window
  # - quad2dpole_v0/window_hard
  # # #
  # - acrobot_v0/swing_up_empty
  # - acrobot_v0/swing_up_obs
  # - acrobot_v0/swing_up_obs_hard
  # - acrobot_v0/swing_down_easy
  # - acrobot_v0/swing_down
  #
  #
  #
  # # # # # # #  QUADROTOR_0
  # - quadrotor_v0/empty_0_easy
  # - quadrotor_v0/empty_1_easy
  # - quadrotor_v0/window
  # - quadrotor_v0/recovery
  # - quadrotor_v0/recovery_with_obs
  # - quadrotor_v0/quad_one_obs
  # # # # # # # # quadrotor_ompl
  # - quadrotor_v1/empty_0_easy
  # - quadrotor_v1/empty_1_easy
  # - quadrotor_v1/window
  # - quadrotor_v1/recovery
  # - quadrotor_v1/quad_one_obs
  # - quadrotor_v1/recovery_with_obs

algs:

  # Idbastar
  # - idbastar_v0
  # - geo_v0
  - sst_v0


  # - idbastar_tmp

  # SST*
  # - sst_tmp
  # - sst_v1
  # - sst_v2
  # - sst_v3
  # - sst_v4
  # - sst_v1t
  # - sst_v2t
  # - sst_v3t
  #
  #
  #
  # # GEO
  # - geo_v1
  # # #
  # #
  # #
  # # - "idbastar_v0_mpcc"
  # # - "idbastar_v0_search"
  # # - "idbastar_v0_heu1"
  # # -  "idbastar_v1" # NOT USEFUL YET!!
